---
- name: Start data container
  shell: "docker create --volume /srv --name pmm-data percona/pmm-server:2 /bin/true"

- name: Start PMM
  shell: "docker run --detach --restart always --publish 80:80 --publish 443:443 --volumes-from pmm-data --name pmm-server percona/pmm-server:2"
